[package]
name = "hyper-tls"
version = "0.1.2"
description = "Default TLS implementation for use with hyper"
authors = ["Sean McArthur <sean.monstar@gmail.com>"]
license = "MIT/Apache-2.0"
keywords = ["hyper", "tls", "http", "https", "ssl"]
homepage = "https://hyper.rs"
repository = "https://github.com/hyperium/hyper-tls"
documentation = "https://docs.rs/hyper-tls"

[dependencies]
futures = "0.1.11"
native-tls = { git = "https://github.com/scottschroeder/rust-native-tls", branch = 'noverify' }
hyper = "0.11"
tokio-core = "0.1.6"
tokio-io = "0.1"
tokio-service = "0.1"
tokio-tls = { git = "https://github.com/scottschroeder/tokio-tls", branch = 'noverify' }
